### ISSUE TITLE
Identify target journals and article types

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit-publication#1]
In my experience it's helpful to know the word count and document structure requirements of the target journal(s) before writing too much content.

Some discussion of this topic at https://discourse.pystatgen.org/t/where-to-publish-an-sgkit-manuscript/72.

**Comment by jeromekelleher** [comment]
One high-level point: I'd vote against going for the short-form application note format like they have in Bioinformatics. They are too short to have any meaningful discussion, IMO.

**Comment by jeromekelleher** [comment]
I'm going to close this, as we've made the decision for the moment I think.
