### ISSUE TITLE
Building locally

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#14]
I'm having real trouble building this locally, not being a conda user (and not wanting to be one). I just tried making a local conda install just for this, but it doesn't seem like this is possible (it insists on updating your shell globally).

Did you manage to get it working @tomwhite?

I thought I got it working initially, but it seems that I was naively assuming that no errors meant that it was working.

It all seems very fragile unfortunately, and I have very little confidence any of it will work in a few months let alone a few years. I'm sure pandoc is solid, but there's numerous layers built on top of that which have loads of complicated version dependencies.

I wonder if we could switch to a simple latex document (especially if I'm going to be doing most of the writing)?

**Comment by tomwhite** [comment]
I used conda and the instructions for building locally: https://github.com/pystatgen/sgkit-publication#local-execution.

I actually get an error when building the PDF, but the HTML builds fine, so I was looking at that.

Another way of doing things would be to push updates and have CI build the manuscript (the PDF works there). I think we can do that as long as we organise a review later on in the process.

I'm also fine with writers using whatever they like to get words out in the lowest friction way for them. We can reorganise later.

**Comment by jeromekelleher** [comment]
What about references? I'm pretty reluctant to spend a bunch of time learning a new referencing system, especially when it seems likely there'll be issues transferring to the final version for typesetting. Latex isn't perfect, but at least it's well known and somewhat supported by journals.

Like I say, if someone else is taking the lead on writing I'm happy to use whatever toolchain suits them best, but if it's me I'm not really interested in beta testing new stuff.

**Comment by tomwhite** [comment]
I don't have experience of different referencing systems so will defer to others.


> Like I say, if someone else is taking the lead on writing I'm happy to use whatever toolchain suits them best, but if it's me I'm not really interested in beta testing new stuff.

Makes sense!

**Comment by timothymillar** [comment]
FWIW, I'm also more comfortable with LaTeX.

**Comment by jeromekelleher** [comment]
OK, let's talk about this at today's meeting.

**Comment by jeromekelleher** [comment]
We discussed this at today's dev meeting (@benjeffery, @hammer, @tomwhite and @ravwojdyla) and agreed that a switch to latex is the most appropriate.

I'll open another issue to track.
