### ISSUE TITLE
Change to latex build

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#16]
After discussion  in #14 we decided that manubot wasn't really solving any problems that we had, and was introducing a bunch of others that we didn't need.

I'm planning to convert to a latex document following the approximate pattern used in this https://github.com/tskit-dev/msprime-1.0-paper

@tomwhite - I seem to remember you had some edits in a fork somewhere - can you open a PR so we can merge them now, if so?

**Comment by jeromekelleher** [comment]
Would anyone mind if I just nuke the git history and start fresh here? It's confusing having all this manubot stuff in the history, and will make it harder to see later on who has contributed what.

I've just gone through the history, and the only things we've really added are the popgen stuff from @tomwhite and a bit of outline content from @eric-czech. The easiest thing to do would be copy this content into a new latex doc, and start with a fresh history, but this would lose the commits from Tom and Eric. If that seems too drastic, I can try to keep the handful of commits that we've made to the repo ourselves, and start from there?

**Comment by tomwhite** [comment]
Fine by me
