### ISSUE TITLE
Data model diagram

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#21]
We want to discuss the fundamentals of sgkit's design choices and data model early on, and it would be helpful to have a figure to clarify these.

The [data model diagram](https://pystatgen.github.io/sgkit/latest/_images/data-structures-xarray.jpg) from the docs seems like a great start. @eric-czech, do you have the original source for this diagram, so we can add it to this repo (and make it easy to tweak)?

See also #5

**Comment by eric-czech** [comment]
> do you have the original source for this diagram

Certainly, the diagram is at https://docs.google.com/drawings/d/1NheB6LCvvkB4C0nAoSFwoYVZ3mtOPaseGmg_mZvcQ8I.

There's a link to it mentioned at https://github.com/pystatgen/sgkit/blob/07e75c20b9b8a4d18ea85d830e4911156aecd0bf/docs/getting_started.rst#L48.

**Comment by jeromekelleher** [comment]
Would you mind opening a pr to drop it into this repo please @eric-czech,  just so we have correct attribution? Doesn't matter where, I can move stuff around later

**Comment by eric-czech** [comment]
Not sure I follow.  An export of the diagram is in the repo at [data-structures-xarray.jpg](https://github.com/pystatgen/sgkit/blob/07e75c20b9b8a4d18ea85d830e4911156aecd0bf/docs/_static/data-structures-xarray.jpg) but any edits to it would have to be made via Google Drawings by copying [this](https://docs.google.com/drawings/d/1NheB6LCvvkB4C0nAoSFwoYVZ3mtOPaseGmg_mZvcQ8I/edit), editing, and re-exporting.

**Comment by jeromekelleher** [comment]
Right, gotcha. I didn't click that there wasn't a source file to check in
