### ISSUE TITLE
Include SAV in data scaling figure

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#38]
We'll inevitably get pinged as pushing BCF as a straw man in the data scaling figure. We can include SAV easily enough.

Code in this repo: https://github.com/jeromekelleher/ga4gh-variant-sim/blob/main/data/Makefile

We could also compare the time for ``sav stat`` to our other calculations, but it wouldn't be directly comparable and I don't have much interest in trying to write C++ for it.

https://github.com/statgen/savvy

**Comment by benjeffery** [comment]
I've made a start on this in #45. It's looking straight forward - the AF dist results are identical to the python implementation. Need to add it to the plots now - perf is about x2 faster than sgkit, but that is preliminary.

**Comment by jeromekelleher** [comment]
Awesome. What's the preliminary results on data-scaling? I'd expect basically the same as sgkit?

**Comment by jeromekelleher** [comment]
Your VCF isn't one of the simulated ones then?

**Comment by benjeffery** [comment]
No, just a 1000g one. Will report back on results for simulated ones.

**Comment by benjeffery** [comment]
For the simulated data sgkit is about 40% bigger than savvy.

**Comment by jeromekelleher** [comment]
Oh, OK. Looks like all those rare variants in the FCs suits savvy well. That's fine.

Good to get an updated results file for the first few data points as soon as we can, so that I can start writing the story around that.

**Comment by benjeffery** [comment]
Yep, working on the code to add the lines to the plots. 
I'm thinking that small chunks will also be hurting compression wise, so I think checking both perf and storage as a function of chunk size needs doing to check we're not leaving big gains on the floor here. Will file that under a separate issue though.

**Comment by jeromekelleher** [comment]
SGTM.

**Comment by benjeffery** [comment]
Preliminary results - sav is still writing to the 1,000,000 file, so that will increase a little

![Screenshot from 2023-12-06 09-34-16](https://github.com/pystatgen/sgkit-publication/assets/8552/217b6471-1655-4087-98a8-eec2fafe6b51)

**Comment by jeromekelleher** [comment]
The sgkit bump at 10**4 is weird - I don't see that in the numbers I have.

![fig1](https://github.com/pystatgen/sgkit-publication/assets/2664569/9a46cfd6-da34-4658-82b8-b932c1e46021)

The filesize numbers shouldn't change for sgkit here (unless you've tweaked the chunk size?)

**Comment by benjeffery** [comment]
Seems I had incompete sgkit folders somehow. Fixed now:
![Screenshot at 2023-12-06 12-46-59](https://github.com/pystatgen/sgkit-publication/assets/8552/8432f563-f069-4f7d-aba5-a4a3c99a0d4f)
Savvy is still writing the 10^6 file. I'm confused about how I saw a larger sgkit file when I converted one by hand, but these figures are based on direct copy of your sgkit files now.

**Comment by jeromekelleher** [comment]
Nice - how's the perf figure looking at these sizes? (Happy to pause the savvy conversion for 10^6, just want to know what the overall story is going to be)

**Comment by jeromekelleher** [comment]
How hard would it be to also do the performance analysis with just the first (say) 100 samples? Does savvy have support for accessing subsets of the samples?

I'm finding myself talking about how accessing the samples is important a lot, and it would be nice to make that point in a more direct way that just saying it helps us parallelise well with Dask.

We could push the threading stuff to a supplementary figure (or another panel?), because it's perhaps a bit confusing to show here anyway if we're going to add a third tool.

**Comment by benjeffery** [comment]
I can easily subset samples by ID in the savvy code. Would be very interesting as sgkit should do well there, especially if the samples are a contiguous block.

**Comment by jeromekelleher** [comment]
Awesome, would be great if you could have a go at that so please

**Comment by jeromekelleher** [comment]
We could try to be ultra-fair too and select 100 randomly chosen samples, so that it's a worst-case for sgkit. I doubt that'll make any difference to BCF, but curious to see if savvy supports efficient sample subsetting (i.e., can pull stuff for those 100 samples off disk without fully decoding the variant).

**Comment by benjeffery** [comment]
If their model is a list of non-ref genotypes, then I can't see how they avoid iterating over all the samples without some other index - which isn't mentioned in their description.
I'll code that up after I've got savvy perf timing in - just working on it now to pull out the variant count to pass to savvy.

**Comment by jeromekelleher** [comment]
> SAV files are indexed using a sort-tile-recursive one-dimensional r-tree (S1R) index file. Genomic regions are organized into an r-tree to enable fast random access to an SAV file without having to traverse the entire index file. Each leaf entry in the tree points to a zstd compressed block in the corresponding SAV file. The entry also encodes the number of variant records in the block, which can be variable depending on the parameters for compressing the SAV file

Sounds like savvy just stores a single record per variant, and so incurs full decode cost each time regardless of subsetting.

**Comment by benjeffery** [comment]
![Screenshot from 2023-12-06 17-46-56](https://github.com/pystatgen/sgkit-publication/assets/8552/bde1346b-a369-4ef6-9dd7-6fcfad966dd4)

Savvy is pretty fast!

**Comment by jeromekelleher** [comment]
That's the released version of sgkit, right? Compare perf with version I showed above.

**Comment by jeromekelleher** [comment]
Interesting! Looks like it's just Python/numba compilation overhead that's the difference for small sample sizes, and they basically converge for larger data. 

*Great* to see the threading results match up so well also!

**Comment by benjeffery** [comment]
![Screenshot from 2023-12-07 09-48-20](https://github.com/pystatgen/sgkit-publication/assets/8552/64422f69-767a-4740-b4ab-9d953e589b6b)

:hot_pepper:

**Comment by jeromekelleher** [comment]
This is done now, closing.
