### ISSUE TITLE
Make data model fig higher level with chunking

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#46]
Currently figure 1 looks like this:

![Screenshot from 2023-12-05 09-58-59](https://github.com/pystatgen/sgkit-publication/assets/2664569/2e7125ba-e7b5-46a3-a6c7-6a81e271210d)

This is a useful overview of the data model, but I think it would be better to focus on illustrating the high-level approach of chunked compression, and the landscape of our major dependencies and what they do. This is going to be a crucial thing to communicate, I think.  Chunked-compressed is obvious to us, but we'll need to explain it to the majority of our readers. Here's my first (terrible) sketch:

![PXL_20231205_102153735](https://github.com/pystatgen/sgkit-publication/assets/2664569/87c8eaf1-23b5-4d4a-8ff0-a7f5bc813ca9)

So we illustrate that we have a regular grid of chunks corresponding to the genotype matrix (Zarr), and each of these chunks is passed through some compressors and filters from numcodecs (best in class, zstd). These chunks are then written to some key/value store: files, cloud blobs, some NoSQL DB, whatever.

What my picture here doesn't show is how xarray fits into this. Ideally, I guess we'd have another layer wrapping around this showing the xarray dataset, which contains a bunch of these variables, and that is the primary object for sgkit.

From the "reader who just looks at the figures" perspective, I think this would be super-helpful and be the necessary prerequisite for understanding Figure 2 (how well this works in terms of storage and basic compute performance).

What do we think?

Unfortunately, this is *way* beyond my graphic design skills and I would need someone else to make this. Any ideas who might be a good person for this?

**Comment by timothymillar** [comment]
@jeromekelleher, I've had a go at this with tikz. I'm very much a novice with tikz, but able to copy-paste may way through it. Happy to refine it further if you think it's on the right track.

![zarr](https://github.com/pystatgen/sgkit-publication/assets/14065102/5b1b14cb-69d2-4659-b322-998ef2bf0892)

**Comment by jeromekelleher** [comment]
Looks great, thanks @timothymillar! I can hack at tikz a bit too, so it's quite helpful for me to do it this way.


The only crucial thing that's missing I think is the "destination" of the chunks. I want to show that chunks can be stored in the file system, a cloud store, a Zip file, or some other key-value store. Decoupling chunk storage from the actual data format is a really key design choice in Zarr, which I want to emphasise. In practise, this means that you can tweak the details of your chunk storage to the application and hardware, which keeping client computation code totally agnostic (which is awesome, and not really possible with anything else).

**Comment by timothymillar** [comment]
Thanks @jeromekelleher. here's an updated attempt. The source is available [here](https://gist.github.com/timothymillar/8ebb2e7a8a60e2d0872b7af7cafc11af). I'll open a PR when it's a little closer.
![call_genotype_chunked_Zarr](https://github.com/pystatgen/sgkit-publication/assets/14065102/585cb54d-4e19-4735-8aa7-4e9d4e6372e4)

**Comment by jeromekelleher** [comment]
Looks great @timothymillar - let's PR it in and see how it looks in the figure! (I'm AFK for a few weeks now though)
