### ISSUE TITLE
Change target journal to GigaScience?

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#49]
For various reasons, eLife may no longer be such a good choice of venue for this paper.

[GigaScience](https://academic.oup.com/gigascience/pages/instructions_to_authors) seems like a natural place for this paper, and lots of good large-scale genomics stuff has been published there (htslib paper, etc).

From the instructions:

> GigaScience is an online open access, open data, open peer-review journal. Our focus covers ‘big data’ research from the life and biomedical sciences, including the growing range of work that uses difficult-to-access large-scale data, such as imaging, neuroscience, ecology, cohort, systems biology, and other new types of sharable data. 

This seems ideal to me?

I guess there is a strategic question about what kind of paper we write: do we write a paper targeted at a large population of end-users which skims over technical details, and tries to highlight ergnomics etc, or do we write a paper targeted at a technically sophisticated audience that's more focused on the strengths of the tech stack?

Personally, I would be more interested (and would find it *much* easier to write) a paper that gets into the technical details. In reality users need to be reasonably sophisticated to use sgkit currently (certainly at scale), and maybe trying to sell sgkit as a user-friendly toolkit for the masses isn't the right angle for now.

**Comment by hammer** [comment]
Fine by me!

**Comment by jeromekelleher** [comment]
Awesome. The story that's emerging is very giga-science oriented, so glad you're on board.
