### ISSUE TITLE
Display items

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit-publication#5]
As discussed in https://github.com/pystatgen/sgkit/discussions/954, here's a potential figure outline for the paper (excluding figures that support use cases):

### Figure 1: PyData ecosystem
- Something like the figures in [The road ahead for scientific computing with Python](https://www.slideshare.net/RalfGommers/the-road-ahead-for-scientific-computing-with-python) from Ralf Gommers?

### Figure 2: Data model
- [Eric's data model diagram](https://pystatgen.github.io/sgkit/latest/_images/data-structures-xarray.jpg)
- I feel like we have the original someplace if we need to edit it?

### Figure 3: API
- High-level overview of the sections and methods implemented in sgkit

### Figure 4: Scale
- Liangde's repo: https://github.com/LiangdeLI/benchmark_public
- [Liangde's thesis](https://github.com/pystatgen/sgkit-publication/files/10058446/Thesis_LiangdeLi.2.pdf)

**Comment by jeromekelleher** [comment]
Closing this as out-of-date
