### ISSUE TITLE
Generalise title

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-publication#82]
Currently the title is: Scalable statistical genetic data analysis in Python

However, we are quite a bit broader than "statistical genetics", so how about something like:

Scalable analysis of genetic variation data in Python

**Comment by hammer** [comment]
For further abstraction, given that a lot of the story is about Zarr and its interoperability, we could also drop the Python part...

**Comment by jeromekelleher** [comment]
I've thought about this, and I think it's better to keep the "Python" here because we're not actually demonstrating scalability outside of Python. It's more like we're pointing out the inherent limitations in existing approaches, and showing that Zarr has a lot of potential as an interoperable compute substrate. Demonstrating actual interoperable scalability in something other than Python (i.e. in a cluster) would be hard.
